"use strict";
const $ = id => document.getElementById(id), selected = new Set();
let data=null, activeParams=null, page=1, tableView=false, busy=false;
const pageSize=6, money=n=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const format=n=>n==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const median=values=>{const a=values.filter(v=>v!=null).sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2:null;};
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
function art(id){
  const colors=[['#e6e9df','#a6b0a0','#74887b'],['#eee4d8','#c8ad8c','#a78362'],['#e2e8ea','#a4b7bc','#778f98']][Number(id)%3];
  return `<div class="property-art"><span class="art-label">SCHEMATIC / SAMPLE ${esc(id)}</span><svg viewBox="0 0 320 140" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="320" height="140" fill="${colors[0]}"/><circle cx="269" cy="43" r="21" fill="#ffffff" opacity=".42"/><path d="M0 121H320V140H0Z" fill="${colors[1]}" opacity=".4"/><path d="M51 119L267 125L298 135H86Z" fill="${colors[2]}" opacity=".14"/><path d="M68 80L135 34L200 80Z" fill="${colors[2]}"/><path d="M80 78L135 44L190 78V121H80Z" fill="#f6f5ed"/><path d="M190 77H250V121H190Z" fill="${colors[1]}"/><path d="M186 71H254V78H186Z" fill="${colors[2]}"/><rect x="126" y="86" width="24" height="35" fill="${colors[2]}"/><rect x="96" y="84" width="19" height="22" fill="${colors[1]}"/><rect x="161" y="84" width="18" height="22" fill="${colors[1]}"/><rect x="203" y="87" width="32" height="20" fill="#f1f1e8"/><path d="M105 84V106M96 95H115M170 84V106M161 95H179M219 87V107" stroke="#fafbf6" stroke-width="2"/><path d="M39 119V80M282 120V94" stroke="${colors[2]}" stroke-width="3"/><ellipse cx="39" cy="79" rx="14" ry="22" fill="${colors[2]}"/><ellipse cx="282" cy="93" rx="12" ry="17" fill="${colors[1]}"/><path d="M126 121L114 140H161L150 121" fill="#faf9f0" opacity=".7"/></svg></div>`;
}
function filters(){return {search:$('search').value.trim().toLowerCase(),budget:Number($('budget').value),beds:Number($('beds').value),area:Number($('area').value),sort:$('sort').value};}
function matches(){
  const f=filters();
  const rows=(data?.listings||[]).filter(r=>(!f.search||r.address.toLowerCase().includes(f.search))&&r.values.price!=null&&r.values.price<=f.budget&&r.values.beds!=null&&r.values.beds>=f.beds&&(!f.area||(r.values.sqft||0)>=f.area));
  return rows.sort((a,b)=>f.sort==='area-desc'?b.values.sqft-a.values.sqft:f.sort==='price-desc'?b.values.price-a.values.price:a.values.price-b.values.price);
}
function compareButton(r){return `<button class="compare-button" data-id="${esc(r.id)}" aria-pressed="${selected.has(r.id)}" aria-label="${selected.has(r.id)?'Remove':'Compare'} ${esc(r.address.split(',')[0])}">${selected.has(r.id)?'✓ Added to compare':'+ Compare'}</button>`;}
function card(r){const [street,...city]=r.address.split(',');return `<article class="property-card">${art(r.id)}<div class="property-main"><div class="property-price">${money(r.values.price)}</div><h3>${esc(street)}</h3><p>${esc(city.join(',').trim())}</p><div class="property-details"><span><b>${format(r.values.beds)}</b> beds</span><span><b>${r.values.baths??'—'}</b> baths</span><span><b>${format(r.values.sqft)}</b> sq ft</span></div></div><div class="property-footer"><span>${money(r.values.sqft?r.values.price/r.values.sqft:null)} / sq ft</span>${compareButton(r)}</div></article>`;}
function updateExport(rows){const link=$('export');link.setAttribute('aria-disabled',!rows.length||busy);if(!rows.length||busy){link.removeAttribute('href');return;}const params=new URLSearchParams(activeParams);Object.entries(filters()).forEach(([k,v])=>params.set(k,v));link.href=`/api/export?${params}`;link.setAttribute('download','habitat_listings_demo.xlsx');}
function bindCompare(){document.querySelectorAll('.compare-button').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.id;if(selected.has(id)){selected.delete(id);}else if(selected.size<3){selected.add(id);}else{message('You can compare up to three properties. Remove one to add another.');return;}message('');render();}));}
function renderCompare(){
  const rows=(data?.listings||[]).filter(r=>selected.has(r.id));$('compare-count').textContent=rows.length;$('clear-compare').disabled=!rows.length;
  $('comparison').innerHTML=rows.length?rows.map(r=>`<article class="compare-card">${art(r.id)}<div class="property-main"><div class="property-price">${money(r.values.price)}</div><h3>${esc(r.address.split(',')[0])}</h3><p>${esc(r.address.split(',').slice(1).join(',').trim())}</p></div><div class="compare-stats">${[['Bedrooms',format(r.values.beds)],['Bathrooms',r.values.baths??'—'],['Floor area',`${format(r.values.sqft)} sq ft`],['Asking price / sq ft',money(r.values.sqft?r.values.price/r.values.sqft:null)],['Collection date',esc(r.date_scraped)]].map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('')}</div><div class="property-footer"><span>Synthetic property</span>${compareButton(r)}</div></article>`).join(''):'<div class="comparison-empty">Your comparison is empty. Add up to three properties from Explore.</div>';
}
function render(){
  const rows=matches(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);const start=(page-1)*pageSize,shown=rows.slice(start,start+pageSize);
  $('total').textContent=rows.length;$('total-note').textContent=`Of ${data?.listings.length||0} extracted properties`;$('median').textContent=money(median(rows.map(r=>r.values.price)));$('price-area').textContent=money(median(rows.map(r=>r.values.sqft?r.values.price/r.values.sqft:null)));$('median-area').textContent=format(median(rows.map(r=>r.values.sqft)));
  $('showing').textContent=`${rows.length} matching ${rows.length===1?'property':'properties'}`;$('cards').innerHTML=shown.map(card).join('');$('cards').hidden=tableView||!rows.length;$('table-wrapper').hidden=!tableView||!rows.length;$('empty').hidden=Boolean(rows.length);
  $('table-rows').innerHTML=shown.map(r=>`<tr><td>${esc(r.address.split(',')[0])}<small>${esc(r.address.split(',').slice(1).join(',').trim())}</small></td><td>${money(r.values.price)}</td><td>${format(r.values.beds)}</td><td>${r.values.baths??'—'}</td><td>${format(r.values.sqft)}</td><td>${compareButton(r)}</td></tr>`).join('');
  $('page-note').textContent=rows.length?`Showing ${start+1}–${Math.min(start+pageSize,rows.length)} of ${rows.length}`:'No matching properties';$('page-number').textContent=`${page} / ${pages}`;$('previous').disabled=page<=1;$('next').disabled=page>=pages;
  updateExport(rows);renderCompare();bindCompare();
}
function resetFilters(){$('search').value='';$('budget').value='800000';$('beds').value='0';$('area').value='0';$('sort').value='price-asc';page=1;}
function renderPipeline(){const s=data.stats;$('pages').textContent=s.pages;$('duplicates').textContent=s.duplicates;$('excluded').textContent=s.excluded;$('pipeline-mode').textContent=s.mode;$('pipeline-status').textContent='✓ Extraction complete';const events=[['Prepared source fixtures',`${s.pages} generated HTML pages. Zero external requests.`],...s.events.map(e=>[`Parsed page ${String(e.page).padStart(2,'0')}`,`${e.parsed} cards parsed · ${e.added} new matching properties retained.`]),['Normalized the collection',`${s.duplicates} repeated listings removed. Prices and room counts checked against the extraction criteria.`],['Ready to explore and export',`${data.listings.length} unique properties. Excel exports reflect your current filters and sort order.`]];$('events').innerHTML=events.map(([title,detail],i)=>`<li><span class="step">${i+1}</span><div><b>${esc(title)}</b><p>${esc(detail)}</p></div></li>`).join('');}
async function run(event){event?.preventDefault();if(busy)return;busy=true;$('run').disabled=true;$('run').textContent='Extracting…';updateExport([]);message('Parsing locally generated property pages…');const params=new URLSearchParams({city:$('city').value,count:$('count').value});try{const response=await fetch(`/api/demo?${params}`),payload=await response.json();if(!response.ok)throw new Error(payload.error||'Extraction failed.');data=payload;activeParams=params;selected.clear();resetFilters();$('run-city').textContent=data.city;$('collection-title').textContent=`Homes in ${data.city}`;$('run-summary').textContent=`${data.listings.length} properties · ${data.stats.pages} pages · ${data.stats.duplicates} duplicates removed`;message('');renderPipeline();}catch(error){message(error.message,true);}finally{busy=false;$('run').disabled=false;$('run').innerHTML='Run extraction <span>→</span>';if(data)render();}}
document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b===button);if(b===button)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelectorAll('.view').forEach(view=>view.hidden=view.id!==`${button.dataset.view}-view`);message('');}));
['search','budget','beds','area','sort'].forEach(id=>$(id).addEventListener('input',()=>{page=1;render();}));$('reset').addEventListener('click',()=>{resetFilters();render();});$('run-form').addEventListener('submit',run);$('previous').addEventListener('click',()=>{page--;render();});$('next').addEventListener('click',()=>{page++;render();});$('view-toggle').addEventListener('click',()=>{tableView=!tableView;$('view-toggle').textContent=tableView?'Card view':'Table view';render();});$('clear-compare').addEventListener('click',()=>{selected.clear();render();});$('export').addEventListener('click',event=>{if($('export').getAttribute('aria-disabled')==='true')event.preventDefault();});run();
